config/routes.rb
Rails.application.routes.draw do


  root                'static_pages#home'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :entries
  resources :relationships,       only: [:create, :destroy]
  resources :comments
end

app/views/shared/_comment_form.html.erb
<% if logged_in? && (current_user.following?(@entry.user) || current_user == @entry.user) %>
    <%= form_for(@comment) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div><%= f.hidden_field :entry_id, :value => @entry.id %></div>
        <div class="field">
          <%= f.label "Comment :" %>
          <%= f.text_field :content, placeholder: "Compose new a comment..." %>
        </div>
        <%= f.submit "Comment", class: "btn btn-primary" %>
    <% end %>
<% end %>

app/views/shared/_entry_form.html.erb
<%= form_for(@entry) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "Compose a title..." %>
    <%= f.text_area :body, placeholder: "Compose a body..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="entries">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.entries.count, "entry") %></span>